# -*- coding: utf-8 -*-
"""image filtering

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/177sFv8JQMmHArUHqojtKKnu4Sz_n549A
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np


def customized_image(image, k_s=3, p=0, s=1):

    # Create average filter kernel
    kernel = np.ones((k_s, k_s), dtype=np.float32) / (k_s ** 2)

    # Add padding if required
    if p > 0:
        image = cv2.copyMakeBorder(
            image, p, p, p, p,
            cv2.BORDER_CONSTANT,
            value=0
        )

    # Calculate output size
    m = ((image.shape[0] - k_s) // s) + 1
    n = ((image.shape[1] - k_s) // s) + 1

    # Create output image
    filtered_image = np.zeros((m, n), dtype=np.float32)

    # Apply filter manually
    for i in range(m):
        for j in range(n):

            # Extract small region
            region = image[
                i*s:i*s+k_s,
                j*s:j*s+k_s
            ]

            # Apply kernel
            filtered_image[i, j] = np.sum(kernel * region)

    return filtered_image


# Read image
img = cv2.imread("/content/ex.jpg", cv2.IMREAD_GRAYSCALE)

# Apply customized filter
filtered = customized_image(img, k_s=3, p=0, s=1)


# Display images
plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.imshow(img, cmap='gray')
plt.title("Original Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(filtered, cmap='gray')
plt.title("Filtered Image")
plt.axis("off")

plt.show()